field: 27a42825-a247-4f3e-9426-5dfbf106c6b8
fieldLayouts:
  bccf5cfd-0384-43fa-ac9d-45f2ca2d3e60:
    tabs:
      -
        elements:
          -
            fieldUid: 852193ba-5b6a-4831-9049-0c5df3b4ef7e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b51210b1-6e7c-473a-865b-5a4a57eeaaf5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  852193ba-5b6a-4831-9049-0c5df3b4ef7e:
    contentColumnType: text
    fieldGroup: null
    handle: copy
    instructions: ''
    name: Copy
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b51210b1-6e7c-473a-865b-5a4a57eeaaf5:
    contentColumnType: text
    fieldGroup: null
    handle: attribution
    instructions: ''
    name: Attribution
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: quote
name: Quote
sortOrder: 6
