field: 27a42825-a247-4f3e-9426-5dfbf106c6b8
fieldLayouts:
  c1508789-ddc1-499b-8d3d-3cd0b645382d:
    tabs:
      -
        elements:
          -
            fieldUid: 75aa4874-70fa-4f11-8472-12521082e2f4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  75aa4874-70fa-4f11-8472-12521082e2f4:
    contentColumnType: string
    fieldGroup: null
    handle: files
    instructions: ''
    name: Files
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:5d3d09ff-0c90-413e-a9ca-4282574853fa'
      defaultUploadLocationSubpath: ''
      limit: '2'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:5d3d09ff-0c90-413e-a9ca-4282574853fa'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: twoImage
name: 'Two Images'
sortOrder: 4
