field: 27a42825-a247-4f3e-9426-5dfbf106c6b8
fieldLayouts:
  e5c1c5a8-5613-48b0-8cf8-5eb1c60325be:
    tabs:
      -
        elements:
          -
            fieldUid: 028374d8-6cdd-4d8c-92c2-bde76f0fc8d1
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e086bce8-ade7-477a-8dbb-3ea14fc6b683
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  028374d8-6cdd-4d8c-92c2-bde76f0fc8d1:
    contentColumnType: string
    fieldGroup: null
    handle: file
    instructions: ''
    name: File
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - video
      defaultUploadLocationSource: 'volume:5d3d09ff-0c90-413e-a9ca-4282574853fa'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:5d3d09ff-0c90-413e-a9ca-4282574853fa'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  e086bce8-ade7-477a-8dbb-3ea14fc6b683:
    contentColumnType: boolean
    fieldGroup: null
    handle: autoplay
    instructions: ''
    name: 'Autoplay & Mute'
    searchable: false
    settings:
      default: true
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: video
name: Video
sortOrder: 5
