field: 27a42825-a247-4f3e-9426-5dfbf106c6b8
fieldLayouts:
  f63baa8f-ccff-41a8-b6d8-cf908bc2c87d:
    tabs:
      -
        elements:
          -
            fieldUid: c2de8ff0-cbd3-4186-8233-d9bdfa5ad099
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d062e329-cab4-4b9f-a1a7-b92ad6463f3a
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  c2de8ff0-cbd3-4186-8233-d9bdfa5ad099:
    contentColumnType: string
    fieldGroup: null
    handle: file
    instructions: ''
    name: File
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - video
      defaultUploadLocationSource: 'volume:5d3d09ff-0c90-413e-a9ca-4282574853fa'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:5d3d09ff-0c90-413e-a9ca-4282574853fa'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  d062e329-cab4-4b9f-a1a7-b92ad6463f3a:
    contentColumnType: boolean
    fieldGroup: null
    handle: autoplay
    instructions: ''
    name: 'Autoplay & Mute'
    searchable: false
    settings:
      default: true
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: video
name: Video
sortOrder: 5
