contentColumnType: text
fieldGroup: 4786e833-776f-4918-a9ee-d816bfa108f8
handle: client
instructions: ''
name: Client
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
