contentColumnType: text
fieldGroup: e78aa093-6e3c-4f9f-8322-bc57755b10ff
handle: copy
instructions: ''
name: Copy
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  cleanupHtml: '1'
  columnType: text
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: Morris.json
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
