contentColumnType: string
fieldGroup: dfa8b3da-8e00-4e78-84c4-76dea5b226f3
handle: entries
instructions: ''
name: Entries
searchable: true
settings:
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  sources: '*'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
