contentColumnType: string
fieldGroup: e78aa093-6e3c-4f9f-8322-bc57755b10ff
handle: externalWork
instructions: ''
name: 'External Work'
searchable: true
settings:
  contentTable: '{{%matrixcontent_externalwork}}'
  maxBlocks: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: none
type: craft\fields\Matrix
