contentColumnType: text
fieldGroup: dfa8b3da-8e00-4e78-84c4-76dea5b226f3
handle: feedLink
instructions: ''
name: Link
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
