contentColumnType: string
fieldGroup: e78aa093-6e3c-4f9f-8322-bc57755b10ff
handle: feed
instructions: ''
name: Feed
searchable: true
settings:
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  sources:
    - 'section:258dfdca-89df-4214-aa69-87c884a9ef01'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
