contentColumnType: text
fieldGroup: 0874a977-d328-4891-9591-ed7a475d9ac0
handle: gdprText
instructions: ''
name: 'GDPR Text'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  cleanupHtml: true
  columnType: text
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: Morris.json
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
