contentColumnType: text
fieldGroup: null
handle: map
instructions: ''
name: Map
searchable: true
settings:
  boundary: '""'
  boundaryRestrictionNELat: null
  boundaryRestrictionNELng: null
  boundaryRestrictionSWLat: null
  boundaryRestrictionSWLng: null
  country: null
  countryRestriction: null
  height: null
  hideAddress: false
  hideLatLng: null
  hideMap: ''
  hideSearch: false
  lat: 0
  lng: 0
  maxZoom: 18
  minZoom: 3
  showLatLng: false
  size: normal
  typeRestriction: null
  zoom: 0
translationKeyFormat: null
translationMethod: none
type: ether\simplemap\fields\MapField
