contentColumnType: string
fieldGroup: 4786e833-776f-4918-a9ee-d816bfa108f8
handle: relatedWork
instructions: ''
name: 'Related Work'
searchable: true
settings:
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  sources:
    - 'section:07e587f7-9a33-4cec-a60d-9f984e64255b'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
