contentColumnType: string
fieldGroup: 4786e833-776f-4918-a9ee-d816bfa108f8
handle: relatedResearch
instructions: ''
name: 'Related Research'
searchable: true
settings:
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  sources:
    - 'section:6cf3bac8-f744-4e07-a84f-bc8148d95883'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
