contentColumnType: string
fieldGroup: 4786e833-776f-4918-a9ee-d816bfa108f8
handle: searchTags
instructions: ''
name: Tags
searchable: true
settings:
  localizeRelations: false
  selectionLabel: ''
  source: 'taggroup:be563fad-62e9-41da-b736-91bde96d142b'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Tags
