contentColumnType: string
fieldGroup: 04850218-a15b-4929-aeb6-de8fd5cbdce0
handle: slides
instructions: ''
name: Slides
searchable: true
settings:
  defaultUploadLocationSource: 'volume:5d3d09ff-0c90-413e-a9ca-4282574853fa'
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  restrictFiles: ''
  selectionLabel: ''
  singleUploadLocationSource: 'volume:5d3d09ff-0c90-413e-a9ca-4282574853fa'
  singleUploadLocationSubpath: ''
  sources:
    - 'volume:5d3d09ff-0c90-413e-a9ca-4282574853fa'
  useSingleFolder: ''
  viewMode: large
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
