contentColumnType: string
fieldGroup: e78aa093-6e3c-4f9f-8322-bc57755b10ff
handle: studioTeam
instructions: ''
name: 'Studio Team'
searchable: true
settings:
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  sources:
    - 'section:3bda0071-f6ff-439a-ae78-161c009e9ddd'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
