enableVersioning: true
handle: map
name: Map
propagationMethod: all
siteSettings:
  17808e62-8917-49fe-bdc9-0160f24e5332:
    enabledByDefault: true
    hasUrls: true
    template: map
    uriFormat: map
  eed39bce-29a0-4ce8-8920-cc743c55a6f1:
    enabledByDefault: true
    hasUrls: true
    template: map
    uriFormat: map
type: single
